"use client";

import React from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { 
  Sparkles, 
  LayoutGrid, 
  FileText, 
  Search, 
  Sliders, 
  Globe, 
  ArrowRight, 
  ArrowLeft,
  CheckCircle
} from "lucide-react";
import { Button } from "../../../components/ui/Button";

const detailedFeatures = [
  {
    icon: Sparkles,
    title: "AI Website Generation",
    subtitle: "Turn words into fully functional stores",
    description: "Our core AI generator processes your store name, business domain, and descriptions to assemble custom page structures. It builds responsive banners, maps direct customer pathways, and programs interactive action elements automatically.",
    details: [
      "Zero coding required to configure layouts",
      "Tailored section structures built for high sales conversion",
      "Instant site assembling and background asset generation"
    ],
    color: "from-emerald-500/10 to-teal-500/10",
    border: "hover:border-emerald-500/30"
  },
  {
    icon: LayoutGrid,
    title: "Dynamic Templates",
    subtitle: "Tailored designs matching your industry vertical",
    description: "Bypass flat, generic wireframes. SiteForge deploys responsive, dynamic grids specialized for local sectors: bakeries, boutique salons, family diners, device showrooms, and grocery outlets. Layout grids rearrange dynamically to emphasize key offers.",
    details: [
      "Preloaded catalog sections for popular item groups",
      "Highly responsive templates optimized for mobile screens",
      "Dynamic components like catalog filters and sliders"
    ],
    color: "from-green-500/10 to-emerald-500/10",
    border: "hover:border-green-500/30"
  },
  {
    icon: FileText,
    title: "AI Content Generation",
    subtitle: "High-impact copywriting and menu catalog builders",
    description: "Struggling to find the right words? Our copy generator writes high-converting product headlines, service descriptions, menu catalog tags, and business stories in regional Indian languages (Hindi, Kannada, Tamil, Telugu, and more).",
    details: [
      "Custom product cards written for local appeal",
      "Auto-populated tags, currency formatting, and prices",
      "Multilingual translation built into the generation stream"
    ],
    color: "from-teal-500/10 to-cyan-500/10",
    border: "hover:border-teal-500/30"
  },
  {
    icon: Search,
    title: "SEO Optimization",
    subtitle: "Out-of-the-box local search visibility",
    description: "Every site generated by SiteForge conforms to the latest Web Vitals and SEO checklists. We automatically output structured JSON-LD schema, generate search-friendly URL handles, configure robots.txt, and write meta tags targeted for local Google maps search.",
    details: [
      "Perfect score of 99/100 on Core Web Vitals speed tests",
      "Automated local business schema tags",
      "Self-updating sitemaps mapped directly to Google Index"
    ],
    color: "from-sky-500/10 to-teal-500/10",
    border: "hover:border-sky-500/30"
  },
  {
    icon: Sliders,
    title: "Template Customization",
    subtitle: "Granular styling via drag-and-drop & color pickers",
    description: "Need to make styling adjustments? Swap color palettes, change font families, re-arrange sections, customize layout spaces, and upload custom banners in seconds using our simplified, user-friendly live visual editor.",
    details: [
      "Theme swapping between minimalist, modern, and warm vibes",
      "Flexible drag-and-drop list re-ordering",
      "Real-time preview of edits prior to going live"
    ],
    color: "from-indigo-500/10 to-teal-500/10",
    border: "hover:border-indigo-500/30"
  },
  {
    icon: Globe,
    title: "Website Publishing",
    subtitle: "Deploy to a global CDN with a single click",
    description: "Ready to launch? SiteForge handles server provisioning, domain bindings, and edge deployments under the hood. Publish on a free siteforge.app domain or bind your custom business domain with an included free SSL certificate.",
    details: [
      "Hosted on high-speed serverless CDNs",
      "Auto-renewing SSL certificate included",
      "Unlimited monthly traffic hosting with sub-second page loads"
    ],
    color: "from-blue-500/10 to-teal-500/10",
    border: "hover:border-blue-500/30"
  }
];

export default function AIWebsiteBuilderPage() {
  return (
    <div className="py-12 md:py-16 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
      
      {/* Back navigation link */}
      <div className="mb-8">
        <Link 
          href="/" 
          className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#354F52] hover:text-[#2F3E46] transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          <span>Back to Homepage</span>
        </Link>
      </div>

      {/* Hero section inside feature page */}
      <div className="max-w-3xl mb-16 space-y-6">
        <div className="inline-flex items-center gap-2 rounded-full border border-[#52796F]/30 bg-[#52796F]/10 px-4 py-1.5 text-xs font-bold text-[#52796F]">
          <Sparkles className="h-3.5 w-3.5" />
          <span>Magical Website Builder</span>
        </div>
        <h1 className="font-display text-4xl sm:text-5xl font-black text-[#2F3E46] leading-tight tracking-tight">
          Create, Customise, and <br />
          Publish in Seconds with AI
        </h1>
        <p className="text-base sm:text-lg text-[#354F52] max-w-2xl leading-relaxed">
          SiteForge replaces expensive web agency retainers. By pairing artificial intelligence 
          with responsive design systems, our AI builds high-speed, localized catalogs tailored 
          to turn casual searchers into customers.
        </p>
      </div>

      {/* Key Feature breakdown cards grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-20">
        {detailedFeatures.map((feat, idx) => {
          const Icon = feat.icon;
          return (
            <motion.div
              key={idx}
              whileHover={{ y: -6 }}
              className={`rounded-[32px] border border-[#2F3E46]/12 bg-white/70 backdrop-blur-md p-8 flex flex-col justify-between shadow-sm transition-all duration-300 ${feat.border}`}
            >
              <div className="space-y-6">
                {/* Header Icon */}
                <div className={`h-12 w-12 rounded-2xl bg-gradient-to-br ${feat.color} border border-[#2F3E46]/10 flex items-center justify-center text-[#52796F]`}>
                  <Icon className="h-6 w-6" />
                </div>
                
                {/* Text Title & Subtitle */}
                <div className="space-y-2">
                  <h3 className="font-display text-xl font-bold text-[#2F3E46]">
                    {feat.title}
                  </h3>
                  <p className="text-[10px] text-zinc-400 font-bold uppercase tracking-wider">
                    {feat.subtitle}
                  </p>
                  <p className="text-xs text-[#354F52] leading-relaxed pt-2">
                    {feat.description}
                  </p>
                </div>

                <hr className="border-[#2F3E46]/10" />

                {/* Sublist details */}
                <ul className="space-y-3.5">
                  {feat.details.map((detail, dIdx) => (
                    <li key={dIdx} className="flex items-start gap-2.5 text-[11px] text-[#354F52] font-semibold">
                      <CheckCircle className="h-4 w-4 text-[#84A98C] shrink-0 mt-0.5" />
                      <span>{detail}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </motion.div>
          );
        })}
      </div>

      {/* Bottom CTA container */}
      <div className="rounded-[40px] bg-[#2F3E46] text-white p-8 sm:p-12 relative overflow-hidden shadow-xl">
        <div className="absolute inset-0 bg-gradient-to-tr from-[#52796F]/10 to-transparent" />
        
        <div className="relative z-10 max-w-2xl space-y-6 text-left">
          <h2 className="font-display text-2xl sm:text-3xl font-extrabold text-white">
            Ready to generate your shop site?
          </h2>
          <p className="text-xs sm:text-sm text-[#CAD2C5] leading-relaxed">
            No credit card is required. Launch a free storefront, customize it in minutes, 
            and start receiving checkout lists on WhatsApp.
          </p>
          <div className="pt-2">
            <Link href="/sign-up">
              <button className="h-12 px-8 rounded-full bg-[#52796F] hover:bg-[#84A98C] text-white font-extrabold text-xs uppercase tracking-wider flex items-center justify-center gap-2 shadow-md transition-all duration-200">
                Generate Free Website <ArrowRight className="h-4 w-4" />
              </button>
            </Link>
          </div>
        </div>
      </div>

    </div>
  );
}
