"use client";

import React from "react";
import { motion } from "framer-motion";
import { Star, Quote, ChevronRight } from "lucide-react";

const testimonials = [
  {
    name: "Rohan Sharma",
    role: "Owner, Sharma Sweet Palace",
    business: "Sweet Shop & Cafe",
    location: "Jaipur, Rajasthan",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop",
    quote: "We wanted a digital menu for home delivery but agencies wanted Rs. 20,000. With SiteForge, I described our sweets menu, and in 2 minutes the website was live. Our customers order directly on WhatsApp now!",
    stars: 5,
    url: "sharmasweets.siteforge.app"
  },
  {
    name: "Anjali Mehta",
    role: "Founder, Bloom Organic Salon",
    business: "Beauty & Spa",
    location: "Mumbai, Maharashtra",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&auto=format&fit=crop",
    quote: "The voice editor is magical. I just said 'change the price of basic haircut to 350 rupees' and it updated immediately. SiteForge makes it incredibly simple to run our website without any tech skills.",
    stars: 5,
    url: "bloomsalon.siteforge.app"
  },
  {
    name: "Karan Johar",
    role: "Manager, Alpha Fitness",
    business: "Gym & Health Club",
    location: "Bangalore, Karnataka",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&auto=format&fit=crop",
    quote: "Our gym site looks outstanding. The dark mode theme generated by the AI perfectly matches our fitness club's branding. Members can view schedules and register instantly from their phones.",
    stars: 5,
    url: "alphagym.siteforge.app"
  },
  {
    name: "Priya Nair",
    role: "Creator, Thread & Craft",
    business: "Fashion Boutique",
    location: "Kochi, Kerala",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=150&auto=format&fit=crop",
    quote: "Our Instagram catalog was messy. Having a structured SiteForge catalog website has increased our credibility. We received over 80 custom inquiries in the first week alone.",
    stars: 5,
    url: "threadcraft.siteforge.app"
  }
];

export default function Testimonials() {
  return (
    <section className="py-24 bg-white border-t border-[#2F3E46]/12 relative overflow-hidden">
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 w-[400px] h-[400px] bg-[#84A98C]/5 rounded-full blur-[120px] pointer-events-none" />

      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
          <h2 className="font-display text-sm font-semibold tracking-wider text-[#52796F] uppercase">
            Success Stories
          </h2>
          <p className="font-display text-3xl sm:text-4xl font-extrabold tracking-tight text-[#2F3E46]">
            Loved By Local Business Owners
          </p>
          <p className="text-[#354F52] text-sm sm:text-base">
            See how small stores, boutique vendors, and local shops across India are launching premium websites, 
            driving sales, and taking direct orders using SiteForge.
          </p>
        </div>

        {/* Horizontal Scrolling wrapper */}
        <div className="flex gap-6 overflow-x-auto pb-10 scrollbar-thin snap-x snap-mandatory relative px-2">
          {testimonials.map((test, idx) => (
            <motion.div
              key={idx}
              className="flex-shrink-0 w-full sm:w-[380px] snap-center rounded-[32px] border border-[#84A98C] bg-white p-8 flex flex-col justify-between hover:border-[#52796F] hover:shadow-md transition-all duration-350 shadow-sm relative"
            >
              <Quote className="absolute right-6 top-6 h-12 w-12 text-[#84A98C] opacity-20 pointer-events-none" />

              <div className="space-y-4">
                {/* Stars and Business badge */}
                <div className="flex justify-between items-center">
                  <div className="flex gap-0.5">
                    {[...Array(test.stars)].map((_, sIdx) => (
                      <Star key={sIdx} className="h-4 w-4 fill-[#52796F] text-[#52796F]" />
                    ))}
                  </div>
                  <span className="text-[8px] bg-[#52796F]/10 border border-[#52796F]/20 text-[#52796F] font-extrabold px-2.5 py-1 rounded-full uppercase tracking-wider">
                    {test.business}
                  </span>
                </div>

                {/* Quote Text */}
                <p className="text-[#354F52] text-xs sm:text-sm leading-relaxed italic">
                  “{test.quote}”
                </p>
              </div>

              {/* Profile Details */}
              <div className="mt-8 pt-6 border-t border-[#2F3E46]/10 flex items-center gap-4">
                <img
                  src={test.image}
                  alt={test.name}
                  className="h-10 w-10 rounded-full object-cover border border-[#2F3E46]/10"
                />
                <div className="flex-1 min-w-0">
                  <h4 className="font-extrabold text-[#2F3E46] text-xs sm:text-sm truncate">{test.name}</h4>
                  <p className="text-[10px] text-zinc-400 font-medium truncate">{test.role}</p>
                  <p className="text-[9px] text-[#52796F] font-bold uppercase tracking-wider mt-0.5">{test.location}</p>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Small horizontal swipe indicator */}
        <div className="flex justify-center items-center gap-2 text-[9px] font-bold uppercase tracking-wider text-[#354F52] mt-4">
          <span>Swipe to browse</span>
          <ChevronRight className="h-3.5 w-3.5 text-[#52796F] animate-pulse" />
        </div>

      </div>
    </section>
  );
}
